/*
 * Copyright (c) 2023 Geo-Studios and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 only, as published
 * by the Free Software Foundation. Geo-Studios designates this particular
 * file as subject to the "Classpath" exception as provided
 * by Geo-Studio in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License version 2 for more details (a copy is
 * included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this work; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package jdk.localedata.share.classes.sun.text.resources.ext;


import jdk.localedata.share.classes.sun.util.resources.Openjava.util.ListResourceBundle;















//  Note: this file has been generated by a tool.




public class JavaTimeSupplementary_ar_JO extends OpenListResourceBundle {
    @Override
    protected final Object[][] getContents() {
        final String[] sharedMonthNames = {
            "\u0643\u0627\u0646\u0648\u0646 \u0627\u0644\u062b\u0627\u0646\u064a",
            "\u0634\u0628\u0627\u0637",
            "\u0622\u0630\u0627\u0631",
            "\u0646\u064a\u0633\u0627\u0646",
            "\u0623\u064a\u0627\u0631",
            "\u062d\u0632\u064a\u0631\u0627\u0646",
            "\u062a\u0645\u0648\u0632",
            "\u0622\u0628",
            "\u0623\u064a\u0644\u0648\u0644",
            "\u062a\u0634\u0631\u064a\u0646 \u0627\u0644\u0623\u0648\u0644",
            "\u062a\u0634\u0631\u064a\u0646 \u0627\u0644\u062b\u0627\u0646\u064a",
            "\u0643\u0627\u0646\u0648\u0646 \u0627\u0644\u0623\u0648\u0644",
            "",
        };

        return new Object[][] {
            { "roc.MonthAbbreviations",
                sharedMonthNames },
            { "roc.MonthNames",
                sharedMonthNames },
            { "roc.MonthNarrows",
                new String[] {
                    "\u0643",
                    "\u0634",
                    "\u0622",
                    "\u0646",
                    "\u0623",
                    "\u062d",
                    "\u062a",
                    "\u0622",
                    "\u0623",
                    "\u062a",
                    "\u062a",
                    "\u0643",
                    "",
                }
            },
        };
    }
}
