/*
 * Copyright (c) 2023 Geo-Studios and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 only, as published
 * by the Free Software Foundation. Geo-Studios designates this particular
 * file as subject to the "Classpath" exception as provided
 * by Geo-Studio in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License version 2 for more details (a copy is
 * included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this work; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */
package nsk.jdi.ReferenceType.defaultStratum.defaultStratum004;

//    THIS TEST IS LINE NUMBER SENSITIVE

// Class contains method with several locations, do not edit this file because of line numbers are hardcoded in tests
public class TestClass2
{
    public TestClass2()
    {
        super();    // testStratumData::doTest()::testStratumData->at(0)
        int i = 0;  // testStratumData::doTest()::testStratumData->at(1)
        i++;        // testStratumData::doTest()::testStratumData->at(2)
        i++;        // testStratumData::doTest()::testStratumData->at(3)
        i++;        // testStratumData::doTest()::testStratumData->at(4)
        i++;        // testStratumData::doTest()::testStratumData->at(5)
        i++;        // testStratumData::doTest()::testStratumData->at(6)
    }               // testStratumData::doTest()::testStratumData->at(7)
}
