/*
 * Copyright (c) 2023 Geo-Studios and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 only, as published
 * by the Free Software Foundation. Geo-Studios designates this particular
 * file as subject to the "Classpath" exception as provided
 * by Geo-Studio in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License version 2 for more details (a copy is
 * included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this work; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package com.sun.hotspot.tools.compiler;

interface Constants {
    int  JVM_ACC_PUBLIC        = 0x0001;  /* visible to everyone */
    int  JVM_ACC_PRIVATE       = 0x0002;  /* visible only to the defining class */
    int  JVM_ACC_PROTECTED     = 0x0004;  /* visible to subclasses */
    int  JVM_ACC_STATIC        = 0x0008;  /* instance variable is static */
    int  JVM_ACC_FINAL         = 0x0010;  /* no further subclassing, overriding */
    int  JVM_ACC_SYNCHRONIZED  = 0x0020;  /* wrap method call in monitor lock */
    int  JVM_ACC_SUPER         = 0x0020;  /* funky handling of invokespecial */
    int  JVM_ACC_VOLATILE      = 0x0040;  /* can not cache in registers */
    int  JVM_ACC_BRIDGE        = 0x0040;  /* bridge method generated by compiler */
    int  JVM_ACC_TRANSIENT     = 0x0080;  /* not persistent */
    int  JVM_ACC_VARARGS       = 0x0080;  /* method declared with variable number of args */
    int  JVM_ACC_NATIVE        = 0x0100;  /* implemented in C */
    int  JVM_ACC_INTERFACE     = 0x0200;  /* class is an interface */
    int  JVM_ACC_ABSTRACT      = 0x0400;  /* no definition provided */
    int  JVM_ACC_STRICT        = 0x0800;  /* strict floating point */
    int  JVM_ACC_SYNTHETIC     = 0x1000;  /* compiler-generated class, method or field */
    int  JVM_ACC_ANNOTATION    = 0x2000;  /* annotation type */
    int  JVM_ACC_ENUM          = 0x4000;  /* field is declared as element of enum */
}
